### PR TITLE
Add 2020-2022 Arsenal badges

### LINKED ISSUE #11: BH Arsenal 2020 badge
Hi,

Are there plans for adding a badge for BH Arsenal 2020 ?

Thanks

### LINKED ISSUE #14: 2020-2022 BH Arsenal badges have not been created
The following Black Hat 2020-2022 badges have not been created.
 
 - 2020
   - BH Asia Arsenal
   - BH USA Arsenal
   - BH Europe Arsenal
 - 2021
   - BH Asia Arsenal
   - BH USA Arsenal
   - BH Europe Arsenal (this badge is pull requested #11 / #13  )
- 2022(prepare)
   - BH Asia Arsenal
   - BH Europe Arsenal
   - BH USA Arsenal

### PR DESCRIPTION
**Pull request by hitenkoku**
fixed #14  fixed #11

## What Changed
- Added Following Arsenal Badges
  - 2020
    - BH Asia Arsenal
    - BH USA Arsenal
    - BH Europe Arsenal
  - 2021
    - BH Asia Arsenal
    - BH USA Arsenal
 
  - 2022
    - BH Asia Arsenal
    - BH Europe Arsenal
    - BH USA Arsenal

### CODE REVIEW

**Comment by TheBinitGhimire** [comment]
Can I use the BH Asia 2022 Arsenal badge from this PR in my project repository? Or, should I be waiting till the PR is merged?

**Comment by hitenkoku** [comment]
@TheBinitGhimire 
You can use it, but I would like to delete the branch after the merge.
I think it would be better to use it after the PR has been merged so that the documentation is less likely to be modified.

@toolswatch 
BH Asia 2022 is coming up soon, so may I merge them once the confirmation is complete?

**Comment by hitenkoku** [comment]
@toolswatch  Hi, I'm waiting for your review.
Please let me know if you need more information concerning this matter.

**Comment by hitenkoku** [comment]
@toolswatch  ping

**Review by toolswatch — APPROVED** [review]

**Pull request merged**
